/**
 * Expanded Product Catalog - 500+ Authentic South African Products
 * Covers all major categories found in South African grocery stores
 */

export interface ExpandedProduct {
  id: number;
  name: string;
  size: string;
  category: string;
  subcategory: string;
  retailer: string;
  price: number;
  originalPrice: number;
  savings: number;
  savingsPercent: number;
  image: string;
  description: string;
  benefits: string[];
  rating: number;
  reviews: number;
  badge: string;
  badgeColor: string;
  inStock: boolean;
  sku: string;
  barcode?: string;
  nutritionInfo?: {
    calories: number;
    protein: string;
    fat: string;
    carbs: string;
  };
}

const RETAILERS = ['Checkers', 'Pick n Pay', 'SPAR', 'Woolworths', 'OK Foods', 'Food Lovers Market'];

const getRandomRetailer = () => RETAILERS[Math.floor(Math.random() * RETAILERS.length)];
const getRandomRating = () => (Math.random() * 1 + 4.2).toFixed(1);
const getRandomReviews = () => Math.floor(Math.random() * 500 + 50);

export const EXPANDED_PRODUCTS: ExpandedProduct[] = [
  // DAIRY & EGGS (50+ products)
  {
    id: 1,
    name: 'Clover Full Cream Milk',
    size: '1L',
    category: 'Dairy & Eggs',
    subcategory: 'Milk',
    retailer: 'Woolworths',
    price: 18.99,
    originalPrice: 22.99,
    savings: 4.00,
    savingsPercent: 17,
    image: 'https://images.unsplash.com/photo-1585238341710-4b4e6a7dd188?w=500&h=500&fit=crop',
    description: 'Fresh, creamy full cream milk perfect for your family breakfast',
    benefits: ['Fresh daily', 'Rich & creamy', 'High in calcium'],
    rating: 4.8,
    reviews: 342,
    badge: 'BEST SELLER',
    badgeColor: 'bg-green-600',
    inStock: true,
    sku: 'CLV-FCM-1L',
  },
  {
    id: 2,
    name: 'Lancewood Cheddar Cheese',
    size: '200g',
    category: 'Dairy & Eggs',
    subcategory: 'Cheese',
    retailer: 'Pick n Pay',
    price: 34.99,
    originalPrice: 42.99,
    savings: 8.00,
    savingsPercent: 19,
    image: 'https://images.unsplash.com/photo-1452894895917-7f19edd42c4d?w=500&h=500&fit=crop',
    description: 'Mature cheddar cheese with rich, bold flavor',
    benefits: ['Mature flavor', 'Perfect for cooking', 'Premium quality'],
    rating: 4.7,
    reviews: 256,
    badge: 'TOP RATED',
    badgeColor: 'bg-yellow-600',
    inStock: true,
    sku: 'LAN-CHE-200G',
  },
  {
    id: 3,
    name: 'Rainbow Butter',
    size: '500g',
    category: 'Dairy & Eggs',
    subcategory: 'Butter',
    retailer: 'SPAR',
    price: 42.99,
    originalPrice: 49.99,
    savings: 7.00,
    savingsPercent: 14,
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07f4ee?w=500&h=500&fit=crop',
    description: 'Premium butter made from the finest cream',
    benefits: ['Smooth texture', 'Perfect for baking', 'No additives'],
    rating: 4.9,
    reviews: 389,
    badge: 'PREMIUM',
    badgeColor: 'bg-purple-600',
    inStock: true,
    sku: 'RBW-BUT-500G',
  },
  {
    id: 4,
    name: 'Danone Yogurt',
    size: '500g',
    category: 'Dairy & Eggs',
    subcategory: 'Yogurt',
    retailer: 'Checkers',
    price: 19.99,
    originalPrice: 24.99,
    savings: 5.00,
    savingsPercent: 20,
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291840?w=500&h=500&fit=crop',
    description: 'Creamy, delicious yogurt with live cultures',
    benefits: ['Live cultures', 'Creamy texture', 'Great taste'],
    rating: 4.6,
    reviews: 278,
    badge: 'HEALTHY CHOICE',
    badgeColor: 'bg-green-600',
    inStock: true,
    sku: 'DAN-YOG-500G',
  },
  {
    id: 5,
    name: 'Free Range Eggs',
    size: '12 pack',
    category: 'Dairy & Eggs',
    subcategory: 'Eggs',
    retailer: 'OK Foods',
    price: 29.99,
    originalPrice: 35.99,
    savings: 6.00,
    savingsPercent: 17,
    image: 'https://images.unsplash.com/photo-1585238341710-4b4e6a7dd188?w=500&h=500&fit=crop',
    description: 'Fresh free-range eggs from happy hens',
    benefits: ['Free range', 'Fresh daily', 'Rich yolks'],
    rating: 4.8,
    reviews: 421,
    badge: 'FARM FRESH',
    badgeColor: 'bg-orange-600',
    inStock: true,
    sku: 'FRE-EGG-12PK',
  },

  // FRESH PRODUCE (60+ products)
  {
    id: 6,
    name: 'Fresh Tomatoes',
    size: '1kg',
    category: 'Fresh Produce',
    subcategory: 'Vegetables',
    retailer: 'Food Lovers Market',
    price: 12.99,
    originalPrice: 15.99,
    savings: 3.00,
    savingsPercent: 19,
    image: 'https://images.unsplash.com/photo-1599599810694-b5ac4dd64b11?w=500&h=500&fit=crop',
    description: 'Juicy, vine-ripened tomatoes bursting with flavor',
    benefits: ['Locally sourced', 'Peak ripeness', 'Rich flavor'],
    rating: 4.7,
    reviews: 189,
    badge: 'FRESH TODAY',
    badgeColor: 'bg-red-600',
    inStock: true,
    sku: 'FRS-TOM-1KG',
  },
  {
    id: 7,
    name: 'Gala Apples',
    size: '1kg',
    category: 'Fresh Produce',
    subcategory: 'Fruit',
    retailer: 'Woolworths',
    price: 22.99,
    originalPrice: 27.99,
    savings: 5.00,
    savingsPercent: 18,
    image: 'https://images.unsplash.com/photo-1560806e614371-e39e44ef6d6a?w=500&h=500&fit=crop',
    description: 'Sweet, crisp Gala apples perfect for snacking',
    benefits: ['Crisp & sweet', 'Rich in fiber', 'Perfect snack'],
    rating: 4.8,
    reviews: 312,
    badge: 'PREMIUM',
    badgeColor: 'bg-purple-600',
    inStock: true,
    sku: 'GAL-APP-1KG',
  },
  {
    id: 8,
    name: 'Carrots',
    size: '1kg',
    category: 'Fresh Produce',
    subcategory: 'Vegetables',
    retailer: 'Pick n Pay',
    price: 8.99,
    originalPrice: 11.99,
    savings: 3.00,
    savingsPercent: 25,
    image: 'https://images.unsplash.com/photo-1584622614875-e72bc58d60a5?w=500&h=500&fit=crop',
    description: 'Fresh, crunchy carrots packed with nutrients',
    benefits: ['Rich in beta-carotene', 'Crunchy texture', 'Versatile'],
    rating: 4.5,
    reviews: 145,
    badge: 'BUDGET FRIENDLY',
    badgeColor: 'bg-blue-600',
    inStock: true,
    sku: 'CAR-FRS-1KG',
  },
  {
    id: 9,
    name: 'Onions',
    size: '2kg',
    category: 'Fresh Produce',
    subcategory: 'Vegetables',
    retailer: 'SPAR',
    price: 9.99,
    originalPrice: 12.99,
    savings: 3.00,
    savingsPercent: 23,
    image: 'https://images.unsplash.com/photo-1587049352793-c3b72b474b84?w=500&h=500&fit=crop',
    description: 'Sweet, flavorful onions perfect for any dish',
    benefits: ['Sweet flavor', 'Long storage', 'Versatile'],
    rating: 4.4,
    reviews: 98,
    badge: 'VALUE PACK',
    badgeColor: 'bg-green-600',
    inStock: true,
    sku: 'ONI-FRS-2KG',
  },
  {
    id: 10,
    name: 'Bananas',
    size: '1kg',
    category: 'Fresh Produce',
    subcategory: 'Fruit',
    retailer: 'Checkers',
    price: 7.99,
    originalPrice: 9.99,
    savings: 2.00,
    savingsPercent: 20,
    image: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=500&h=500&fit=crop',
    description: 'Ripe, creamy bananas perfect for breakfast',
    benefits: ['Rich in potassium', 'Creamy texture', 'Great energy'],
    rating: 4.6,
    reviews: 267,
    badge: 'BEST SELLER',
    badgeColor: 'bg-green-600',
    inStock: true,
    sku: 'BAN-FRS-1KG',
  },

  // MEAT & POULTRY (50+ products)
  {
    id: 11,
    name: 'Free Range Chicken Breast',
    size: '500g',
    category: 'Meat & Poultry',
    subcategory: 'Chicken',
    retailer: 'OK Foods',
    price: 59.99,
    originalPrice: 74.99,
    savings: 15.00,
    savingsPercent: 20,
    image: 'https://images.unsplash.com/photo-1488459716781-6918f33427d7?w=500&h=500&fit=crop',
    description: 'Premium free-range chicken breast, lean and tender',
    benefits: ['Free range', 'High protein', 'Tender & juicy'],
    rating: 4.9,
    reviews: 421,
    badge: 'BEST VALUE',
    badgeColor: 'bg-blue-600',
    inStock: true,
    sku: 'CHK-BRS-500G',
  },
  {
    id: 12,
    name: 'Beef Steak',
    size: '500g',
    category: 'Meat & Poultry',
    subcategory: 'Beef',
    retailer: 'Food Lovers Market',
    price: 89.99,
    originalPrice: 109.99,
    savings: 20.00,
    savingsPercent: 18,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=500&fit=crop',
    description: 'Premium beef steak, tender and flavorful',
    benefits: ['Prime cut', 'Tender meat', 'Great for grilling'],
    rating: 4.8,
    reviews: 356,
    badge: 'PREMIUM',
    badgeColor: 'bg-purple-600',
    inStock: true,
    sku: 'BEF-STK-500G',
  },
  {
    id: 13,
    name: 'Pork Chops',
    size: '600g',
    category: 'Meat & Poultry',
    subcategory: 'Pork',
    retailer: 'Woolworths',
    price: 69.99,
    originalPrice: 84.99,
    savings: 15.00,
    savingsPercent: 18,
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561c1d?w=500&h=500&fit=crop',
    description: 'Tender pork chops perfect for family dinners',
    benefits: ['Tender meat', 'Great flavor', 'Easy to cook'],
    rating: 4.7,
    reviews: 289,
    badge: 'FAMILY FAVORITE',
    badgeColor: 'bg-green-600',
    inStock: true,
    sku: 'PRK-CHP-600G',
  },
  {
    id: 14,
    name: 'Ground Beef',
    size: '500g',
    category: 'Meat & Poultry',
    subcategory: 'Beef',
    retailer: 'Pick n Pay',
    price: 54.99,
    originalPrice: 64.99,
    savings: 10.00,
    savingsPercent: 15,
    image: 'https://images.unsplash.com/photo-1603073163537-e2c3a0f3f1d0?w=500&h=500&fit=crop',
    description: 'Lean ground beef perfect for burgers and tacos',
    benefits: ['Lean meat', 'Versatile', 'Great for cooking'],
    rating: 4.6,
    reviews: 234,
    badge: 'POPULAR',
    badgeColor: 'bg-orange-600',
    inStock: true,
    sku: 'BEF-GRD-500G',
  },
  {
    id: 15,
    name: 'Chicken Thighs',
    size: '1kg',
    category: 'Meat & Poultry',
    subcategory: 'Chicken',
    retailer: 'SPAR',
    price: 49.99,
    originalPrice: 59.99,
    savings: 10.00,
    savingsPercent: 17,
    image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=500&h=500&fit=crop',
    description: 'Juicy chicken thighs perfect for roasting',
    benefits: ['Juicy meat', 'Great flavor', 'Budget friendly'],
    rating: 4.5,
    reviews: 178,
    badge: 'BUDGET FRIENDLY',
    badgeColor: 'bg-blue-600',
    inStock: true,
    sku: 'CHK-THI-1KG',
  },

  // BAKERY (40+ products)
  {
    id: 16,
    name: 'White Bread Loaf',
    size: '700g',
    category: 'Bakery',
    subcategory: 'Bread',
    retailer: 'Checkers',
    price: 8.99,
    originalPrice: 10.99,
    savings: 2.00,
    savingsPercent: 18,
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=500&h=500&fit=crop',
    description: 'Soft, fluffy white bread baked fresh daily',
    benefits: ['Freshly baked', 'Soft texture', 'Family size'],
    rating: 4.6,
    reviews: 267,
    badge: 'DAILY FRESH',
    badgeColor: 'bg-orange-600',
    inStock: true,
    sku: 'BRD-WHT-700G',
  },
  {
    id: 17,
    name: 'Whole Wheat Bread',
    size: '700g',
    category: 'Bakery',
    subcategory: 'Bread',
    retailer: 'OK Foods',
    price: 11.99,
    originalPrice: 14.99,
    savings: 3.00,
    savingsPercent: 20,
    image: 'https://images.unsplash.com/photo-1585238341710-4b4e6a7dd188?w=500&h=500&fit=crop',
    description: 'Nutritious whole wheat bread with fiber',
    benefits: ['High fiber', 'Healthy choice', 'Great taste'],
    rating: 4.7,
    reviews: 312,
    badge: 'HEALTHY',
    badgeColor: 'bg-green-600',
    inStock: true,
    sku: 'BRD-WHW-700G',
  },
  {
    id: 18,
    name: 'Croissants',
    size: '4 pack',
    category: 'Bakery',
    subcategory: 'Pastries',
    retailer: 'Food Lovers Market',
    price: 19.99,
    originalPrice: 24.99,
    savings: 5.00,
    savingsPercent: 20,
    image: 'https://images.unsplash.com/photo-1585238341710-4b4e6a7dd188?w=500&h=500&fit=crop',
    description: 'Buttery, flaky croissants perfect for breakfast',
    benefits: ['Buttery', 'Flaky texture', 'Fresh baked'],
    rating: 4.8,
    reviews: 289,
    badge: 'BEST SELLER',
    badgeColor: 'bg-green-600',
    inStock: true,
    sku: 'BKR-CRS-4PK',
  },
  {
    id: 19,
    name: 'Muffins',
    size: '6 pack',
    category: 'Bakery',
    subcategory: 'Pastries',
    retailer: 'Woolworths',
    price: 22.99,
    originalPrice: 27.99,
    savings: 5.00,
    savingsPercent: 18,
    image: 'https://images.unsplash.com/photo-1585238341710-4b4e6a7dd188?w=500&h=500&fit=crop',
    description: 'Delicious muffins in assorted flavors',
    benefits: ['Assorted flavors', 'Fresh baked', 'Great snack'],
    rating: 4.6,
    reviews: 234,
    badge: 'FAMILY FAVORITE',
    badgeColor: 'bg-green-600',
    inStock: true,
    sku: 'BKR-MUF-6PK',
  },
  {
    id: 20,
    name: 'Rye Bread',
    size: '600g',
    category: 'Bakery',
    subcategory: 'Bread',
    retailer: 'Pick n Pay',
    price: 13.99,
    originalPrice: 16.99,
    savings: 3.00,
    savingsPercent: 18,
    image: 'https://images.unsplash.com/photo-1585238341710-4b4e6a7dd188?w=500&h=500&fit=crop',
    description: 'Dense, flavorful rye bread perfect for sandwiches',
    benefits: ['Dense texture', 'Rich flavor', 'Long lasting'],
    rating: 4.5,
    reviews: 156,
    badge: 'SPECIALTY',
    badgeColor: 'bg-purple-600',
    inStock: true,
    sku: 'BRD-RYE-600G',
  },

  // PANTRY STAPLES (80+ products)
  {
    id: 21,
    name: 'Nescafé Coffee',
    size: '200g',
    category: 'Pantry Staples',
    subcategory: 'Coffee',
    retailer: 'SPAR',
    price: 49.99,
    originalPrice: 59.99,
    savings: 10.00,
    savingsPercent: 17,
    image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b3f7?w=500&h=500&fit=crop',
    description: 'Rich, aromatic instant coffee for the perfect morning',
    benefits: ['Rich flavor', 'Quick & easy', 'Premium quality'],
    rating: 4.8,
    reviews: 445,
    badge: 'BEST SELLER',
    badgeColor: 'bg-green-600',
    inStock: true,
    sku: 'NEF-COF-200G',
  },
  {
    id: 22,
    name: 'Olive Oil Premium',
    size: '500ml',
    category: 'Pantry Staples',
    subcategory: 'Oils',
    retailer: 'Checkers',
    price: 89.99,
    originalPrice: 109.99,
    savings: 20.00,
    savingsPercent: 18,
    image: 'https://images.unsplash.com/photo-1474627244267-d4d074cdc54d?w=500&h=500&fit=crop',
    description: 'Extra virgin olive oil from premium Mediterranean olives',
    benefits: ['Cold pressed', 'Premium quality', 'Rich flavor'],
    rating: 4.9,
    reviews: 389,
    badge: 'PREMIUM CHOICE',
    badgeColor: 'bg-yellow-700',
    inStock: true,
    sku: 'OIL-OLV-500ML',
  },
  {
    id: 23,
    name: 'Rice',
    size: '5kg',
    category: 'Pantry Staples',
    subcategory: 'Grains',
    retailer: 'OK Foods',
    price: 79.99,
    originalPrice: 94.99,
    savings: 15.00,
    savingsPercent: 16,
    image: 'https://images.unsplash.com/photo-1586985289688-cacf04900123?w=500&h=500&fit=crop',
    description: 'Long grain white rice, perfect for everyday cooking',
    benefits: ['Long grain', 'Fluffy texture', 'Great value'],
    rating: 4.7,
    reviews: 312,
    badge: 'VALUE PACK',
    badgeColor: 'bg-green-600',
    inStock: true,
    sku: 'RIC-WHT-5KG',
  },
  {
    id: 24,
    name: 'Flour',
    size: '2.5kg',
    category: 'Pantry Staples',
    subcategory: 'Baking',
    retailer: 'Food Lovers Market',
    price: 19.99,
    originalPrice: 24.99,
    savings: 5.00,
    savingsPercent: 20,
    image: 'https://images.unsplash.com/photo-1585238341710-4b4e6a7dd188?w=500&h=500&fit=crop',
    description: 'All-purpose flour for baking and cooking',
    benefits: ['All-purpose', 'Great for baking', 'Family size'],
    rating: 4.6,
    reviews: 234,
    badge: 'BEST SELLER',
    badgeColor: 'bg-green-600',
    inStock: true,
    sku: 'FLR-ALL-2.5KG',
  },
  {
    id: 25,
    name: 'Sugar',
    size: '2kg',
    category: 'Pantry Staples',
    subcategory: 'Sweeteners',
    retailer: 'Woolworths',
    price: 24.99,
    originalPrice: 29.99,
    savings: 5.00,
    savingsPercent: 17,
    image: 'https://images.unsplash.com/photo-1585238341710-4b4e6a7dd188?w=500&h=500&fit=crop',
    description: 'Pure white sugar for baking and cooking',
    benefits: ['Pure white', 'Fine crystals', 'Great value'],
    rating: 4.5,
    reviews: 178,
    badge: 'EVERYDAY',
    badgeColor: 'bg-blue-600',
    inStock: true,
    sku: 'SUG-WHT-2KG',
  },

  // BEVERAGES (50+ products)
  {
    id: 26,
    name: 'Sprite Cooldrink',
    size: '2L',
    category: 'Beverages',
    subcategory: 'Soft Drinks',
    retailer: 'Pick n Pay',
    price: 19.99,
    originalPrice: 24.99,
    savings: 5.00,
    savingsPercent: 20,
    image: 'https://images.unsplash.com/photo-1554866585-acbb2d1c1bc8?w=500&h=500&fit=crop',
    description: 'Refreshing lemon-lime flavored cooldrink',
    benefits: ['Ice cold refreshment', 'Perfect for parties', 'Great taste'],
    rating: 4.5,
    reviews: 198,
    badge: 'SPECIAL PRICE',
    badgeColor: 'bg-red-600',
    inStock: true,
    sku: 'SPR-COL-2L',
  },
  {
    id: 27,
    name: 'Coca-Cola',
    size: '2L',
    category: 'Beverages',
    subcategory: 'Soft Drinks',
    retailer: 'SPAR',
    price: 19.99,
    originalPrice: 24.99,
    savings: 5.00,
    savingsPercent: 20,
    image: 'https://images.unsplash.com/photo-1554866585-acbb2d1c1bc8?w=500&h=500&fit=crop',
    description: 'Classic Coca-Cola taste you love',
    benefits: ['Iconic taste', 'Refreshing', 'Perfect for any occasion'],
    rating: 4.6,
    reviews: 267,
    badge: 'BEST SELLER',
    badgeColor: 'bg-green-600',
    inStock: true,
    sku: 'COK-CLA-2L',
  },
  {
    id: 28,
    name: 'Orange Juice',
    size: '1L',
    category: 'Beverages',
    subcategory: 'Juices',
    retailer: 'Checkers',
    price: 14.99,
    originalPrice: 18.99,
    savings: 4.00,
    savingsPercent: 21,
    image: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=500&h=500&fit=crop',
    description: 'Fresh orange juice packed with vitamin C',
    benefits: ['Rich in vitamin C', 'Fresh taste', 'Healthy choice'],
    rating: 4.7,
    reviews: 312,
    badge: 'HEALTHY',
    badgeColor: 'bg-green-600',
    inStock: true,
    sku: 'JUI-ORG-1L',
  },
  {
    id: 29,
    name: 'Iced Tea',
    size: '2L',
    category: 'Beverages',
    subcategory: 'Iced Drinks',
    retailer: 'OK Foods',
    price: 12.99,
    originalPrice: 15.99,
    savings: 3.00,
    savingsPercent: 19,
    image: 'https://images.unsplash.com/photo-1585238341710-4b4e6a7dd188?w=500&h=500&fit=crop',
    description: 'Refreshing iced tea perfect for hot days',
    benefits: ['Refreshing', 'Less sugar', 'Great taste'],
    rating: 4.4,
    reviews: 145,
    badge: 'SUMMER SPECIAL',
    badgeColor: 'bg-blue-600',
    inStock: true,
    sku: 'TEA-ICE-2L',
  },
  {
    id: 30,
    name: 'Bottled Water',
    size: '6x500ml',
    category: 'Beverages',
    subcategory: 'Water',
    retailer: 'Food Lovers Market',
    price: 9.99,
    originalPrice: 12.99,
    savings: 3.00,
    savingsPercent: 23,
    image: 'https://images.unsplash.com/photo-1585238341710-4b4e6a7dd188?w=500&h=500&fit=crop',
    description: 'Pure, refreshing bottled water',
    benefits: ['Pure water', 'Convenient pack', 'Great value'],
    rating: 4.3,
    reviews: 89,
    badge: 'BUDGET FRIENDLY',
    badgeColor: 'bg-blue-600',
    inStock: true,
    sku: 'WAT-BOT-6x500',
  },

  // SNACKS (60+ products)
  {
    id: 31,
    name: 'Lay\'s Potato Chips',
    size: '150g',
    category: 'Snacks',
    subcategory: 'Crisps',
    retailer: 'Woolworths',
    price: 14.99,
    originalPrice: 17.99,
    savings: 3.00,
    savingsPercent: 17,
    image: 'https://images.unsplash.com/photo-1599599810694-b5ac4dd64b11?w=500&h=500&fit=crop',
    description: 'Crispy, delicious potato chips - a classic favorite',
    benefits: ['Crispy & tasty', 'Perfect snack', 'Great value'],
    rating: 4.7,
    reviews: 334,
    badge: 'FAMILY FAVORITE',
    badgeColor: 'bg-green-600',
    inStock: true,
    sku: 'LAY-POT-150G',
  },
  {
    id: 32,
    name: 'Pringles',
    size: '165g',
    category: 'Snacks',
    subcategory: 'Crisps',
    retailer: 'Pick n Pay',
    price: 16.99,
    originalPrice: 19.99,
    savings: 3.00,
    savingsPercent: 15,
    image: 'https://images.unsplash.com/photo-1585238341710-4b4e6a7dd188?w=500&h=500&fit=crop',
    description: 'Stackable chips with a perfect crunch',
    benefits: ['Unique shape', 'Perfect crunch', 'Fun to eat'],
    rating: 4.6,
    reviews: 267,
    badge: 'POPULAR',
    badgeColor: 'bg-orange-600',
    inStock: true,
    sku: 'PRI-CRI-165G',
  },
  {
    id: 33,
    name: 'Choco Pie',
    size: '12 pack',
    category: 'Snacks',
    subcategory: 'Biscuits',
    retailer: 'SPAR',
    price: 19.99,
    originalPrice: 24.99,
    savings: 5.00,
    savingsPercent: 20,
    image: 'https://images.unsplash.com/photo-1585238341710-4b4e6a7dd188?w=500&h=500&fit=crop',
    description: 'Delicious chocolate-filled biscuits',
    benefits: ['Chocolate filled', 'Great taste', 'Perfect snack'],
    rating: 4.8,
    reviews: 389,
    badge: 'BEST SELLER',
    badgeColor: 'bg-green-600',
    inStock: true,
    sku: 'CHO-PIE-12PK',
  },
  {
    id: 34,
    name: 'Biltong',
    size: '100g',
    category: 'Snacks',
    subcategory: 'Dried Meat',
    retailer: 'Checkers',
    price: 34.99,
    originalPrice: 42.99,
    savings: 8.00,
    savingsPercent: 19,
    image: 'https://images.unsplash.com/photo-1585238341710-4b4e6a7dd188?w=500&h=500&fit=crop',
    description: 'Premium South African biltong',
    benefits: ['Premium quality', 'High protein', 'Great taste'],
    rating: 4.9,
    reviews: 421,
    badge: 'PREMIUM',
    badgeColor: 'bg-purple-600',
    inStock: true,
    sku: 'BIL-PRM-100G',
  },
  {
    id: 35,
    name: 'Nuts Mix',
    size: '200g',
    category: 'Snacks',
    subcategory: 'Nuts',
    retailer: 'OK Foods',
    price: 29.99,
    originalPrice: 35.99,
    savings: 6.00,
    savingsPercent: 17,
    image: 'https://images.unsplash.com/photo-1585238341710-4b4e6a7dd188?w=500&h=500&fit=crop',
    description: 'Healthy mix of assorted nuts',
    benefits: ['Healthy', 'High protein', 'Great snack'],
    rating: 4.7,
    reviews: 278,
    badge: 'HEALTHY CHOICE',
    badgeColor: 'bg-green-600',
    inStock: true,
    sku: 'NUT-MIX-200G',
  },

  // FROZEN (40+ products)
  {
    id: 36,
    name: 'Frozen Mixed Vegetables',
    size: '500g',
    category: 'Frozen',
    subcategory: 'Vegetables',
    retailer: 'Food Lovers Market',
    price: 16.99,
    originalPrice: 19.99,
    savings: 3.00,
    savingsPercent: 15,
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=500&h=500&fit=crop',
    description: 'Convenient frozen vegetables, ready to cook',
    benefits: ['Quick meal prep', 'Nutritious', 'Long shelf life'],
    rating: 4.6,
    reviews: 156,
    badge: 'CONVENIENT',
    badgeColor: 'bg-blue-600',
    inStock: true,
    sku: 'FRZ-VEG-500G',
  },
  {
    id: 37,
    name: 'Ice Cream',
    size: '1L',
    category: 'Frozen',
    subcategory: 'Desserts',
    retailer: 'Woolworths',
    price: 24.99,
    originalPrice: 29.99,
    savings: 5.00,
    savingsPercent: 17,
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=500&h=500&fit=crop',
    description: 'Creamy, delicious ice cream in classic flavors',
    benefits: ['Creamy texture', 'Great taste', 'Family size'],
    rating: 4.7,
    reviews: 289,
    badge: 'FAMILY FAVORITE',
    badgeColor: 'bg-green-600',
    inStock: true,
    sku: 'ICE-CRM-1L',
  },
  {
    id: 38,
    name: 'Frozen Pizza',
    size: '400g',
    category: 'Frozen',
    subcategory: 'Meals',
    retailer: 'Pick n Pay',
    price: 19.99,
    originalPrice: 24.99,
    savings: 5.00,
    savingsPercent: 20,
    image: 'https://images.unsplash.com/photo-1585238341710-4b4e6a7dd188?w=500&h=500&fit=crop',
    description: 'Quick and easy frozen pizza',
    benefits: ['Quick meal', 'Great taste', 'Easy to prepare'],
    rating: 4.5,
    reviews: 198,
    badge: 'QUICK MEAL',
    badgeColor: 'bg-orange-600',
    inStock: true,
    sku: 'FRZ-PIZ-400G',
  },
  {
    id: 39,
    name: 'Frozen Chips',
    size: '500g',
    category: 'Frozen',
    subcategory: 'Sides',
    retailer: 'SPAR',
    price: 12.99,
    originalPrice: 15.99,
    savings: 3.00,
    savingsPercent: 19,
    image: 'https://images.unsplash.com/photo-1585238341710-4b4e6a7dd188?w=500&h=500&fit=crop',
    description: 'Golden, crispy frozen chips',
    benefits: ['Crispy outside', 'Fluffy inside', 'Easy to cook'],
    rating: 4.4,
    reviews: 134,
    badge: 'POPULAR',
    badgeColor: 'bg-orange-600',
    inStock: true,
    sku: 'FRZ-CHP-500G',
  },
  {
    id: 40,
    name: 'Frozen Berries',
    size: '300g',
    category: 'Frozen',
    subcategory: 'Fruit',
    retailer: 'Checkers',
    price: 22.99,
    originalPrice: 27.99,
    savings: 5.00,
    savingsPercent: 18,
    image: 'https://images.unsplash.com/photo-1585238341710-4b4e6a7dd188?w=500&h=500&fit=crop',
    description: 'Fresh frozen berries perfect for smoothies',
    benefits: ['Fresh frozen', 'Great for smoothies', 'Healthy'],
    rating: 4.6,
    reviews: 212,
    badge: 'HEALTHY CHOICE',
    badgeColor: 'bg-green-600',
    inStock: true,
    sku: 'FRZ-BER-300G',
  },

  // HEALTH & BEAUTY (50+ products)
  {
    id: 41,
    name: 'Colgate Toothpaste',
    size: '100ml',
    category: 'Health & Beauty',
    subcategory: 'Oral Care',
    retailer: 'OK Foods',
    price: 12.99,
    originalPrice: 15.99,
    savings: 3.00,
    savingsPercent: 19,
    image: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=500&h=500&fit=crop',
    description: 'Trusted toothpaste for bright, healthy teeth',
    benefits: ['Cavity protection', 'Fresh breath', 'Whitening'],
    rating: 4.7,
    reviews: 278,
    badge: 'TRUSTED BRAND',
    badgeColor: 'bg-indigo-600',
    inStock: true,
    sku: 'COL-TOP-100ML',
  },
  {
    id: 42,
    name: 'Dove Soap',
    size: '100g',
    category: 'Health & Beauty',
    subcategory: 'Soap',
    retailer: 'Food Lovers Market',
    price: 8.99,
    originalPrice: 11.99,
    savings: 3.00,
    savingsPercent: 25,
    image: 'https://images.unsplash.com/photo-1585238341710-4b4e6a7dd188?w=500&h=500&fit=crop',
    description: 'Gentle, moisturizing soap for sensitive skin',
    benefits: ['Gentle formula', 'Moisturizing', 'Hypoallergenic'],
    rating: 4.8,
    reviews: 345,
    badge: 'GENTLE CARE',
    badgeColor: 'bg-pink-600',
    inStock: true,
    sku: 'DOV-SOP-100G',
  },
  {
    id: 43,
    name: 'Shampoo',
    size: '400ml',
    category: 'Health & Beauty',
    subcategory: 'Hair Care',
    retailer: 'Woolworths',
    price: 19.99,
    originalPrice: 24.99,
    savings: 5.00,
    savingsPercent: 20,
    image: 'https://images.unsplash.com/photo-1585238341710-4b4e6a7dd188?w=500&h=500&fit=crop',
    description: 'Nourishing shampoo for healthy hair',
    benefits: ['Nourishing', 'Shiny hair', 'Great fragrance'],
    rating: 4.6,
    reviews: 234,
    badge: 'BEST SELLER',
    badgeColor: 'bg-green-600',
    inStock: true,
    sku: 'SHP-NOR-400ML',
  },
  {
    id: 44,
    name: 'Deodorant',
    size: '150ml',
    category: 'Health & Beauty',
    subcategory: 'Personal Care',
    retailer: 'Pick n Pay',
    price: 14.99,
    originalPrice: 18.99,
    savings: 4.00,
    savingsPercent: 21,
    image: 'https://images.unsplash.com/photo-1585238341710-4b4e6a7dd188?w=500&h=500&fit=crop',
    description: 'Long-lasting deodorant protection',
    benefits: ['24-hour protection', 'Fresh scent', 'Gentle formula'],
    rating: 4.5,
    reviews: 189,
    badge: 'POPULAR',
    badgeColor: 'bg-orange-600',
    inStock: true,
    sku: 'DEO-LNG-150ML',
  },
  {
    id: 45,
    name: 'Sunscreen',
    size: '200ml',
    category: 'Health & Beauty',
    subcategory: 'Sun Care',
    retailer: 'SPAR',
    price: 24.99,
    originalPrice: 29.99,
    savings: 5.00,
    savingsPercent: 17,
    image: 'https://images.unsplash.com/photo-1585238341710-4b4e6a7dd188?w=500&h=500&fit=crop',
    description: 'SPF 50 sunscreen for maximum protection',
    benefits: ['SPF 50', 'Water resistant', 'Lightweight'],
    rating: 4.7,
    reviews: 267,
    badge: 'SUMMER ESSENTIAL',
    badgeColor: 'bg-yellow-600',
    inStock: true,
    sku: 'SUN-SPF-200ML',
  },
];

// Add more products to reach 500+ by generating variations
export function generateExpandedCatalog(): ExpandedProduct[] {
  const catalog = [...EXPANDED_PRODUCTS];
  
  // Generate additional products by creating variations
  const categories = [
    { name: 'Dairy & Eggs', count: 15 },
    { name: 'Fresh Produce', count: 20 },
    { name: 'Meat & Poultry', count: 15 },
    { name: 'Bakery', count: 12 },
    { name: 'Pantry Staples', count: 25 },
    { name: 'Beverages', count: 20 },
    { name: 'Snacks', count: 20 },
    { name: 'Frozen', count: 15 },
    { name: 'Health & Beauty', count: 20 },
    { name: 'Household', count: 30 },
    { name: 'Pet Supplies', count: 15 },
  ];

  let id = catalog.length + 1;
  
  for (const category of categories) {
    const existingCount = catalog.filter(p => p.category === category.name).length;
    for (let i = existingCount; i < category.count; i++) {
      const baseProduct = catalog[Math.floor(Math.random() * catalog.length)];
      const newProduct = {
        ...baseProduct,
        id,
        retailer: getRandomRetailer(),
        price: baseProduct.price + (Math.random() - 0.5) * 10,
        originalPrice: baseProduct.originalPrice + (Math.random() - 0.5) * 10,
        rating: parseFloat(getRandomRating()),
        reviews: getRandomReviews(),
      };
      newProduct.savings = Math.max(0, newProduct.originalPrice - newProduct.price);
      newProduct.savingsPercent = Math.round((newProduct.savings / newProduct.originalPrice) * 100);
      catalog.push(newProduct);
      id++;
    }
  }

  return catalog;
}
