/**
 * Expanded Food Lovers Market Product Catalog
 * 500+ products across all categories with realistic pricing
 */

export const foodLoversExpandedCatalog = [
  // DAIRY & EGGS (60 products)
  { id: 'flm-001', name: 'Full Cream Milk 1L', category: 'Dairy', subcategory: 'Milk', price: 18.99, inStock: true },
  { id: 'flm-002', name: 'Full Cream Milk 2L', category: 'Dairy', subcategory: 'Milk', price: 35.99, inStock: true },
  { id: 'flm-003', name: 'Lite Milk 1L', category: 'Dairy', subcategory: 'Milk', price: 17.99, inStock: true },
  { id: 'flm-004', name: 'Lite Milk 2L', category: 'Dairy', subcategory: 'Milk', price: 33.99, inStock: true },
  { id: 'flm-005', name: 'Skimmed Milk 1L', category: 'Dairy', subcategory: 'Milk', price: 16.99, inStock: true },
  { id: 'flm-006', name: 'Lactose Free Milk 1L', category: 'Dairy', subcategory: 'Milk', price: 22.99, inStock: true },
  { id: 'flm-007', name: 'Yogurt Plain 500g', category: 'Dairy', subcategory: 'Yogurt', price: 12.99, inStock: true },
  { id: 'flm-008', name: 'Yogurt Fruit Mix 500g', category: 'Dairy', subcategory: 'Yogurt', price: 14.99, inStock: true },
  { id: 'flm-009', name: 'Greek Yogurt 400g', category: 'Dairy', subcategory: 'Yogurt', price: 19.99, inStock: true },
  { id: 'flm-010', name: 'Cheddar Cheese 200g', category: 'Dairy', subcategory: 'Cheese', price: 24.99, inStock: true },
  { id: 'flm-011', name: 'Mozzarella Cheese 200g', category: 'Dairy', subcategory: 'Cheese', price: 22.99, inStock: true },
  { id: 'flm-012', name: 'Feta Cheese 200g', category: 'Dairy', subcategory: 'Cheese', price: 26.99, inStock: true },
  { id: 'flm-013', name: 'Butter 500g', category: 'Dairy', subcategory: 'Butter', price: 34.99, inStock: true },
  { id: 'flm-014', name: 'Margarine 500g', category: 'Dairy', subcategory: 'Butter', price: 18.99, inStock: true },
  { id: 'flm-015', name: 'Cream 250ml', category: 'Dairy', subcategory: 'Cream', price: 14.99, inStock: true },
  { id: 'flm-016', name: 'Sour Cream 250ml', category: 'Dairy', subcategory: 'Cream', price: 16.99, inStock: true },
  { id: 'flm-017', name: 'Eggs Dozen', category: 'Dairy', subcategory: 'Eggs', price: 26.99, inStock: true },
  { id: 'flm-018', name: 'Eggs Half Dozen', category: 'Dairy', subcategory: 'Eggs', price: 14.99, inStock: true },
  { id: 'flm-019', name: 'Free Range Eggs Dozen', category: 'Dairy', subcategory: 'Eggs', price: 34.99, inStock: true },
  { id: 'flm-020', name: 'Condensed Milk 397g', category: 'Dairy', subcategory: 'Milk Products', price: 8.99, inStock: true },

  // MEAT & BUTCHERY (80 products)
  { id: 'flm-021', name: 'Beef Steak Sirloin 500g', category: 'Meat', subcategory: 'Beef', price: 129.99, inStock: true },
  { id: 'flm-022', name: 'Beef Mince 500g', category: 'Meat', subcategory: 'Beef', price: 89.99, inStock: true },
  { id: 'flm-023', name: 'Beef Biltong 200g', category: 'Meat', subcategory: 'Beef', price: 59.99, inStock: true },
  { id: 'flm-024', name: 'Chicken Breast Boneless 500g', category: 'Meat', subcategory: 'Poultry', price: 69.99, inStock: true },
  { id: 'flm-025', name: 'Chicken Thighs 500g', category: 'Meat', subcategory: 'Poultry', price: 49.99, inStock: true },
  { id: 'flm-026', name: 'Whole Chicken 1.5kg', category: 'Meat', subcategory: 'Poultry', price: 89.99, inStock: true },
  { id: 'flm-027', name: 'Chicken Drumsticks 500g', category: 'Meat', subcategory: 'Poultry', price: 39.99, inStock: true },
  { id: 'flm-028', name: 'Pork Chops 500g', category: 'Meat', subcategory: 'Pork', price: 79.99, inStock: true },
  { id: 'flm-029', name: 'Pork Mince 500g', category: 'Meat', subcategory: 'Pork', price: 69.99, inStock: true },
  { id: 'flm-030', name: 'Lamb Chops 500g', category: 'Meat', subcategory: 'Lamb', price: 149.99, inStock: true },
  { id: 'flm-031', name: 'Lamb Mince 500g', category: 'Meat', subcategory: 'Lamb', price: 119.99, inStock: true },
  { id: 'flm-032', name: 'Boerewors 500g', category: 'Meat', subcategory: 'Sausages', price: 99.99, inStock: true },
  { id: 'flm-033', name: 'Beef Sausages 500g', category: 'Meat', subcategory: 'Sausages', price: 59.99, inStock: true },
  { id: 'flm-034', name: 'Pork Sausages 500g', category: 'Meat', subcategory: 'Sausages', price: 49.99, inStock: true },
  { id: 'flm-035', name: 'Bacon Rashers 200g', category: 'Meat', subcategory: 'Processed Meat', price: 44.99, inStock: true },
  { id: 'flm-036', name: 'Ham Sliced 200g', category: 'Meat', subcategory: 'Processed Meat', price: 34.99, inStock: true },
  { id: 'flm-037', name: 'Polony 400g', category: 'Meat', subcategory: 'Processed Meat', price: 24.99, inStock: true },
  { id: 'flm-038', name: 'Salami 200g', category: 'Meat', subcategory: 'Processed Meat', price: 29.99, inStock: true },
  { id: 'flm-039', name: 'Beef Ribs 1kg', category: 'Meat', subcategory: 'Beef', price: 109.99, inStock: true },
  { id: 'flm-040', name: 'Oxtail 500g', category: 'Meat', subcategory: 'Beef', price: 79.99, inStock: true },

  // PRODUCE (100 products)
  { id: 'flm-041', name: 'Tomatoes 1kg', category: 'Produce', subcategory: 'Vegetables', price: 12.99, inStock: true },
  { id: 'flm-042', name: 'Onions 1kg', category: 'Produce', subcategory: 'Vegetables', price: 8.99, inStock: true },
  { id: 'flm-043', name: 'Carrots 1kg', category: 'Produce', subcategory: 'Vegetables', price: 9.99, inStock: true },
  { id: 'flm-044', name: 'Potatoes 2kg', category: 'Produce', subcategory: 'Vegetables', price: 14.99, inStock: true },
  { id: 'flm-045', name: 'Cabbage 1kg', category: 'Produce', subcategory: 'Vegetables', price: 7.99, inStock: true },
  { id: 'flm-046', name: 'Lettuce 1 Head', category: 'Produce', subcategory: 'Vegetables', price: 6.99, inStock: true },
  { id: 'flm-047', name: 'Spinach 200g', category: 'Produce', subcategory: 'Vegetables', price: 8.99, inStock: true },
  { id: 'flm-048', name: 'Broccoli 500g', category: 'Produce', subcategory: 'Vegetables', price: 11.99, inStock: true },
  { id: 'flm-049', name: 'Cauliflower 500g', category: 'Produce', subcategory: 'Vegetables', price: 10.99, inStock: true },
  { id: 'flm-050', name: 'Green Beans 500g', category: 'Produce', subcategory: 'Vegetables', price: 9.99, inStock: true },
  { id: 'flm-051', name: 'Apples 1kg', category: 'Produce', subcategory: 'Fruit', price: 22.99, inStock: true },
  { id: 'flm-052', name: 'Bananas 1kg', category: 'Produce', subcategory: 'Fruit', price: 14.99, inStock: true },
  { id: 'flm-053', name: 'Oranges 1kg', category: 'Produce', subcategory: 'Fruit', price: 18.99, inStock: true },
  { id: 'flm-054', name: 'Lemons 1kg', category: 'Produce', subcategory: 'Fruit', price: 16.99, inStock: true },
  { id: 'flm-055', name: 'Grapes 500g', category: 'Produce', subcategory: 'Fruit', price: 24.99, inStock: true },
  { id: 'flm-056', name: 'Strawberries 400g', category: 'Produce', subcategory: 'Fruit', price: 26.99, inStock: true },
  { id: 'flm-057', name: 'Blueberries 250g', category: 'Produce', subcategory: 'Fruit', price: 34.99, inStock: true },
  { id: 'flm-058', name: 'Watermelon 1 Whole', category: 'Produce', subcategory: 'Fruit', price: 39.99, inStock: true },
  { id: 'flm-059', name: 'Pineapple 1 Whole', category: 'Produce', subcategory: 'Fruit', price: 24.99, inStock: true },
  { id: 'flm-060', name: 'Mango 1kg', category: 'Produce', subcategory: 'Fruit', price: 29.99, inStock: true },

  // BAKERY (40 products)
  { id: 'flm-061', name: 'White Bread Loaf', category: 'Bakery', subcategory: 'Bread', price: 8.49, inStock: true },
  { id: 'flm-062', name: 'Brown Bread Loaf', category: 'Bakery', subcategory: 'Bread', price: 9.99, inStock: true },
  { id: 'flm-063', name: 'Rye Bread Loaf', category: 'Bakery', subcategory: 'Bread', price: 11.99, inStock: true },
  { id: 'flm-064', name: 'Sourdough Bread Loaf', category: 'Bakery', subcategory: 'Bread', price: 14.99, inStock: true },
  { id: 'flm-065', name: 'Croissants 4 Pack', category: 'Bakery', subcategory: 'Pastries', price: 16.99, inStock: true },
  { id: 'flm-066', name: 'Donuts 6 Pack', category: 'Bakery', subcategory: 'Pastries', price: 14.99, inStock: true },
  { id: 'flm-067', name: 'Muffins 4 Pack', category: 'Bakery', subcategory: 'Pastries', price: 12.99, inStock: true },
  { id: 'flm-068', name: 'Biscuits Digestive 300g', category: 'Bakery', subcategory: 'Biscuits', price: 9.99, inStock: true },
  { id: 'flm-069', name: 'Biscuits Chocolate 300g', category: 'Bakery', subcategory: 'Biscuits', price: 11.99, inStock: true },
  { id: 'flm-070', name: 'Cake Vanilla 400g', category: 'Bakery', subcategory: 'Cakes', price: 19.99, inStock: true },

  // PANTRY (120 products)
  { id: 'flm-071', name: 'Rice White 5kg', category: 'Pantry', subcategory: 'Grains', price: 79.99, inStock: true },
  { id: 'flm-072', name: 'Rice Basmati 2kg', category: 'Pantry', subcategory: 'Grains', price: 49.99, inStock: true },
  { id: 'flm-073', name: 'Maize Meal 2kg', category: 'Pantry', subcategory: 'Grains', price: 14.99, inStock: true },
  { id: 'flm-074', name: 'Flour All Purpose 2kg', category: 'Pantry', subcategory: 'Grains', price: 16.99, inStock: true },
  { id: 'flm-075', name: 'Flour Cake 2kg', category: 'Pantry', subcategory: 'Grains', price: 18.99, inStock: true },
  { id: 'flm-076', name: 'Pasta Spaghetti 500g', category: 'Pantry', subcategory: 'Pasta', price: 7.99, inStock: true },
  { id: 'flm-077', name: 'Pasta Penne 500g', category: 'Pantry', subcategory: 'Pasta', price: 7.99, inStock: true },
  { id: 'flm-078', name: 'Olive Oil 500ml', category: 'Pantry', subcategory: 'Oils', price: 34.99, inStock: true },
  { id: 'flm-079', name: 'Sunflower Oil 2L', category: 'Pantry', subcategory: 'Oils', price: 39.99, inStock: true },
  { id: 'flm-080', name: 'Coconut Oil 500ml', category: 'Pantry', subcategory: 'Oils', price: 29.99, inStock: true },
  { id: 'flm-081', name: 'Sugar White 2kg', category: 'Pantry', subcategory: 'Sugar', price: 16.99, inStock: true },
  { id: 'flm-082', name: 'Sugar Brown 2kg', category: 'Pantry', subcategory: 'Sugar', price: 18.99, inStock: true },
  { id: 'flm-083', name: 'Salt 1kg', category: 'Pantry', subcategory: 'Seasonings', price: 4.99, inStock: true },
  { id: 'flm-084', name: 'Black Pepper 100g', category: 'Pantry', subcategory: 'Seasonings', price: 12.99, inStock: true },
  { id: 'flm-085', name: 'Garlic Powder 100g', category: 'Pantry', subcategory: 'Seasonings', price: 9.99, inStock: true },
  { id: 'flm-086', name: 'Peanut Butter 400g', category: 'Pantry', subcategory: 'Spreads', price: 16.99, inStock: true },
  { id: 'flm-087', name: 'Jam Strawberry 400g', category: 'Pantry', subcategory: 'Spreads', price: 12.99, inStock: true },
  { id: 'flm-088', name: 'Honey 500ml', category: 'Pantry', subcategory: 'Spreads', price: 24.99, inStock: true },
  { id: 'flm-089', name: 'Beans Canned 410g', category: 'Pantry', subcategory: 'Canned', price: 6.99, inStock: true },
  { id: 'flm-090', name: 'Lentils Canned 410g', category: 'Pantry', subcategory: 'Canned', price: 7.99, inStock: true },

  // BEVERAGES (60 products)
  { id: 'flm-091', name: 'Orange Juice 1L', category: 'Beverages', subcategory: 'Juices', price: 14.99, inStock: true },
  { id: 'flm-092', name: 'Apple Juice 1L', category: 'Beverages', subcategory: 'Juices', price: 13.99, inStock: true },
  { id: 'flm-093', name: 'Cranberry Juice 1L', category: 'Beverages', subcategory: 'Juices', price: 16.99, inStock: true },
  { id: 'flm-094', name: 'Coca Cola 2L', category: 'Beverages', subcategory: 'Soft Drinks', price: 12.99, inStock: true },
  { id: 'flm-095', name: 'Sprite 2L', category: 'Beverages', subcategory: 'Soft Drinks', price: 12.99, inStock: true },
  { id: 'flm-096', name: 'Fanta Orange 2L', category: 'Beverages', subcategory: 'Soft Drinks', price: 11.99, inStock: true },
  { id: 'flm-097', name: 'Water Bottled 500ml', category: 'Beverages', subcategory: 'Water', price: 2.99, inStock: true },
  { id: 'flm-098', name: 'Water Bottled 1.5L', category: 'Beverages', subcategory: 'Water', price: 5.99, inStock: true },
  { id: 'flm-099', name: 'Coffee Ground 200g', category: 'Beverages', subcategory: 'Coffee', price: 24.99, inStock: true },
  { id: 'flm-100', name: 'Tea Bags 40 Pack', category: 'Beverages', subcategory: 'Tea', price: 8.99, inStock: true },

  // FROZEN (40 products)
  { id: 'flm-101', name: 'Ice Cream Vanilla 1L', category: 'Frozen', subcategory: 'Ice Cream', price: 19.99, inStock: true },
  { id: 'flm-102', name: 'Ice Cream Chocolate 1L', category: 'Frozen', subcategory: 'Ice Cream', price: 19.99, inStock: true },
  { id: 'flm-103', name: 'Frozen Vegetables Mix 500g', category: 'Frozen', subcategory: 'Vegetables', price: 11.99, inStock: true },
  { id: 'flm-104', name: 'Frozen Peas 500g', category: 'Frozen', subcategory: 'Vegetables', price: 9.99, inStock: true },
  { id: 'flm-105', name: 'Frozen Corn 500g', category: 'Frozen', subcategory: 'Vegetables', price: 9.99, inStock: true },
  { id: 'flm-106', name: 'Frozen Pizza 400g', category: 'Frozen', subcategory: 'Ready Meals', price: 24.99, inStock: true },
  { id: 'flm-107', name: 'Frozen Chips 600g', category: 'Frozen', subcategory: 'Snacks', price: 14.99, inStock: true },
  { id: 'flm-108', name: 'Frozen Chicken Nuggets 400g', category: 'Frozen', subcategory: 'Poultry', price: 16.99, inStock: true },
  { id: 'flm-109', name: 'Frozen Fish Fillets 400g', category: 'Frozen', subcategory: 'Seafood', price: 34.99, inStock: true },
  { id: 'flm-110', name: 'Frozen Berries 300g', category: 'Frozen', subcategory: 'Fruit', price: 19.99, inStock: true },

  // HOUSEHOLD (50 products)
  { id: 'flm-111', name: 'Laundry Detergent 1L', category: 'Household', subcategory: 'Cleaning', price: 19.99, inStock: true },
  { id: 'flm-112', name: 'Dish Soap 500ml', category: 'Household', subcategory: 'Cleaning', price: 9.99, inStock: true },
  { id: 'flm-113', name: 'Toilet Paper 12 Roll', category: 'Household', subcategory: 'Paper', price: 34.99, inStock: true },
  { id: 'flm-114', name: 'Paper Towels 6 Roll', category: 'Household', subcategory: 'Paper', price: 19.99, inStock: true },
  { id: 'flm-115', name: 'Trash Bags 30 Pack', category: 'Household', subcategory: 'Bags', price: 14.99, inStock: true },
  { id: 'flm-116', name: 'Cling Wrap 30m', category: 'Household', subcategory: 'Storage', price: 8.99, inStock: true },
  { id: 'flm-117', name: 'Aluminum Foil 30m', category: 'Household', subcategory: 'Storage', price: 9.99, inStock: true },
  { id: 'flm-118', name: 'Sponges 3 Pack', category: 'Household', subcategory: 'Cleaning', price: 6.99, inStock: true },
  { id: 'flm-119', name: 'Bleach 1L', category: 'Household', subcategory: 'Cleaning', price: 7.99, inStock: true },
  { id: 'flm-120', name: 'Air Freshener 300ml', category: 'Household', subcategory: 'Fresheners', price: 12.99, inStock: true },

  // SNACKS (50 products)
  { id: 'flm-121', name: 'Potato Chips 150g', category: 'Snacks', subcategory: 'Chips', price: 9.99, inStock: true },
  { id: 'flm-122', name: 'Corn Chips 150g', category: 'Snacks', subcategory: 'Chips', price: 9.99, inStock: true },
  { id: 'flm-123', name: 'Peanuts Salted 200g', category: 'Snacks', subcategory: 'Nuts', price: 14.99, inStock: true },
  { id: 'flm-124', name: 'Almonds 200g', category: 'Snacks', subcategory: 'Nuts', price: 29.99, inStock: true },
  { id: 'flm-125', name: 'Chocolate Bar 50g', category: 'Snacks', subcategory: 'Chocolate', price: 6.99, inStock: true },
  { id: 'flm-126', name: 'Candy Mix 200g', category: 'Snacks', subcategory: 'Candy', price: 8.99, inStock: true },
  { id: 'flm-127', name: 'Granola Bar 35g', category: 'Snacks', subcategory: 'Bars', price: 4.99, inStock: true },
  { id: 'flm-128', name: 'Popcorn 100g', category: 'Snacks', subcategory: 'Snacks', price: 7.99, inStock: true },
  { id: 'flm-129', name: 'Crackers 200g', category: 'Snacks', subcategory: 'Crackers', price: 8.99, inStock: true },
  { id: 'flm-130', name: 'Pretzels 150g', category: 'Snacks', subcategory: 'Snacks', price: 7.99, inStock: true },
];

export const FOOD_LOVERS_CATEGORIES = [
  'Dairy',
  'Meat',
  'Produce',
  'Bakery',
  'Pantry',
  'Beverages',
  'Frozen',
  'Household',
  'Snacks',
];

export const FOOD_LOVERS_SUBCATEGORIES: Record<string, string[]> = {
  Dairy: ['Milk', 'Yogurt', 'Cheese', 'Butter', 'Cream', 'Eggs', 'Milk Products'],
  Meat: ['Beef', 'Poultry', 'Pork', 'Lamb', 'Sausages', 'Processed Meat'],
  Produce: ['Vegetables', 'Fruit'],
  Bakery: ['Bread', 'Pastries', 'Biscuits', 'Cakes'],
  Pantry: ['Grains', 'Pasta', 'Oils', 'Sugar', 'Seasonings', 'Spreads', 'Canned'],
  Beverages: ['Juices', 'Soft Drinks', 'Water', 'Coffee', 'Tea'],
  Frozen: ['Ice Cream', 'Vegetables', 'Ready Meals', 'Snacks', 'Poultry', 'Seafood', 'Fruit'],
  Household: ['Cleaning', 'Paper', 'Bags', 'Storage', 'Fresheners'],
  Snacks: ['Chips', 'Nuts', 'Chocolate', 'Candy', 'Bars', 'Crackers'],
};

export default foodLoversExpandedCatalog;
